name: Check PUA

on:
  schedule:
    # Cada 10 minuts entre les 8:00 i les 19:59
    - cron: "*/10 8-19 * * *"
    # Cada hora entre les 20:00 i les 7:59
    - cron: "0 20-23 * * *"
    - cron: "0 0-7 * * *"
  workflow_dispatch:  # permet executar manualment

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 lxml

      - name: Run script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_GROUP_ID: ${{ secrets.TELEGRAM_GROUP_ID }}
          TELEGRAM_CHAT_IDS: ${{ secrets.TELEGRAM_CHAT_IDS }}
        run: python3 check.py
