name: Check PUA page

on:
  schedule:
    - cron: "*/6 * * * *"
  workflow_dispatch:  # permet executar manualment

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Andorra   # Força la zona horària a CEST

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 lxml pytz

      - name: Run script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_GROUP_ID: ${{ secrets.TELEGRAM_GROUP_ID }}
          TELEGRAM_CHAT_IDS: ${{ secrets.TELEGRAM_CHAT_IDS }}
        run: python3 check.py