name: Check PUA page

on:
  schedule:
    # Cada 5 minuts entre les 8:00 i les 19:59
    - cron: "*/5 8-19 * * *"
    # Cada 30 minuts entre les 20:00 i les 23:59
    - cron: "*/30 20-23 * * *"
    # Cada 30 minuts entre les 0:00 i les 7:59
    - cron: "*/30 0-7 * * *"
  workflow_dispatch:  # permet executar manualment

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Andorra   # Força la zona horària a CEST

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 lxml pytz

      - name: Run script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_GROUP_ID: ${{ secrets.TELEGRAM_GROUP_ID }}
          TELEGRAM_CHAT_IDS: ${{ secrets.TELEGRAM_CHAT_IDS }}
        run: python3 check.py